services:
  izgw-transform:
    image: izgw-transform:latest
    ports:
      - "443:443"
    env_file: ./.env
    volumes:
      - type: bind
        source: ${XFORM_CONFIGURATIONS_DIRECTORY_LOCAL}
        target: ${XFORM_CONFIGURATIONS_DIRECTORY}
      - type: bind
        source: ${SSL_SHARE_LOCAL}
        target: ${SSL_SHARE}
