xform:
  allow-delete-via-api: false
  destination:
    hub:
      uri: ${XFORM_HUB_DESTINATION:https://localhost/IISHubService}
      id: ${XFORM_HUB_DESTINATION_ID:hub}
      type: 5
    iis:
      uri: ${XFORM_IIS_DESTINATION:https://localhost/dev/IISService}
      id: ${XFORM_IIS_DESTINATION_ID:iis}
      type: 5
  configurations:
    organizations: testing/configuration/organizations.json
    pipelines: testing/configuration/pipelines.json
    solutions: testing/configuration/solutions.json
    mappings: testing/configuration/mappings.json
    access-control: testing/configuration/access-control.json
    operation-precondition-fields: testing/configuration/operation-precondition-fields.json
    users: testing/configuration/users.json
    group-role-mapping: testing/configuration/group-role-mapping.json
jwt:
  provider: ${XFORM_JWT_PROVIDER:shared-secret}
  shared-secret: ${XFORM_JWT_SECRET:}
  jwk-set-uri: ${XFORM_JWT_URI:}
  roles-claim: ${XFORM_JWT_ROLES_CLAIM:roles}
  scopes-claim: ${XFORM_JWT_SCOPES_CLAIM:scope}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    banner-mode: off
    # Consider whether this should be turned off in production.
    lazy-initialization: true
  application:
    name: transformation
    fix-newlines: ${FIX_NEWLINES:true}
  servlet:
    multipart:
      enabled: true
      max-file-size: 15GB
      max-request-size: 15GB

elastic:
  api-key: ${ELASTIC_API_KEY:}
  host: ${ELASTIC_HOST:https://audacioussearchtest.es.us-east-1.aws.found.io:9243}
  index: ${ELASTIC_INDEX:izgw-dev-logstash}

v2tofhir:
  sendingApplication: ${SENDING_APPLICATION:FHIR}
  sendingFacility: ${SENDING_FACILITY:DEV}
  receivingApplication: ${RECEIVING_APPLICATION:TEST}
  receivingFacility: ${RECEIVING_FACILITY:MOCK}
  facilityId: ${FACILITY_ID:IZG}

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    defaults:
      enabled: false

security:
  enable-csrf: false
  enable-blacklist: true
  enable-ocsp: false
  # Set to the deployment path of the SSL
  # For test and dev deployments, set SSL_SHARE environment variable to the location of the EFS File system in
  # the AWS environment.
  ssl-path: ${SSL_SHARE:}

springdoc:
  swagger-ui:
    path: /swagger/ui.html
  api-docs:
    path: /swagger/api-docs
  paths-to-match: /api/**

server:
  error:
    include-message: always
  hostname: ${XFORM_SERVER_HOSTNAME:dev.izgateway.org}
  protocol: https
  port: ${XFORM_SERVER_PORT:444}
  local-port: 9082
  ssl:
    enabled: true
    client-auth: want
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3
    ciphers:
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
      - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256



    key-store: ${XFORM_CRYPTO_STORE_KEY_TOMCAT_SERVER_FILE:${security.ssl-path}/awsdev_keystore.bcfks}
    key-store-password: ${COMMON_PASS:}
    key-store-provider: BCFIPS
    key-store-type: bcfks

    trust-store: ${XFORM_CRYPTO_STORE_TRUST_TOMCAT_SERVER_FILE:${security.ssl-path}/awsdev_keystore.bcfks}
    trust-store-password: ${COMMON_PASS:}
    trust-store-provider: BCFIPS
    trust-store-type: bcfks

client:
  contentType: text/xml
  readTimeout: 60
  connectTimeout: 15
  maxBufferSize: 65536
  ssl:
    enabled: true
    client-auth: need
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3
    ciphers:
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
      - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
    key-store: ${XFORM_CRYPTO_STORE_KEY_WS_CLIENT_FILE:${security.ssl-path}/awsdev_keystore.bcfks}
    key-store-password: ${COMMON_PASS:}
    key-store-provider: BCFIPS
    key-store-type: bcfks

    trust-store: ${XFORM_CRYPTO_STORE_TRUST_WS_CLIENT_FILE:${security.ssl-path}/izgw_client_trust.bcfks}
    trust-store-password: ${COMMON_PASS:}
    trust-store-provider: BCFIPS
    trust-store-type: bcfks
    certificate-header: ${CLIENT_CERTIFICATE_HEADER:x-amzn-mtls-clientcert-leaf}

logging:
  file:
    enabled: true
  console:
    pretty: ${PRETTY:false}
    enabled: true
  memory:
    enabled: true

  heartbeat:
    interval: 60

  level:
    gov:
      cdc:
        izgateway:
          xform: ${LOGGING_LEVEL:INFO}
          security:
            AccessControlRegistry: INFO
            AccessControlInterceptor: INFO
            client:
              ClientSecurityInterceptor: INFO
            principal: ${LOGGING_LEVEL:INFO}
            server:
              ServerSecurityInterceptor: INFO
    org:
      springframework:
        web: INFO
      apache:
        tomcat:
          util:
            net:
              NioChannel:
                handshake: DEBUG
