version: '3.1'
services:
  xform:
    image: izgw-transform:latest
    container_name: xform
    ports:
      - '444:444'
    environment:
      COMMON_PASS: "${COMMON_PASS}"
      SSL_SHARE: '/ssl'
      TS_SERVER_PORT: '444'
      TS_HUB_DESTINATION: "${TS_HUB_DESTINATION}"
      ELASTIC_API_KEY: "${ELASTIC_API_KEY}"
      LOGGING_LEVEL: "${LOGGING_LEVEL}"
      transformationservice.configurations.users: "${CONFIG_USERS}"
      transformationservice.configurations.organizations: "${CONFIG_ORGANIZATIONS}"
      transformationservice.configurations.solutions: "${CONFIG_SOLUTIONS}"
      transformationservice.configurations.pipelines: "${CONFIG_PIPELINES}"
    volumes:
      - type: bind
        source: "${SSL_SOURCE}"
        target: /ssl
      - type: bind
        source: "${CONFIG_SOURCE}"
        target: /configuration
    networks:
      - izgw-network
