version: '3.1'
services:
  xform:
    image: izgw-transform:latest
    container_name: xform
    ports:
      - '444:444'
    environment:
      COMMON_PASS: ${COMMON_PASS}
      XFORM_DESTINATION_HUB_URI: ${XFORM_DESTINATION_HUB_URI}
      XFORM_IIS_DESTINATION: ${XFORM_IIS_DESTINATION}
      ELASTIC_API_KEY: ${ELASTIC_API_KEY}
      XFORM_SERVER_PORT: ${XFORM_SERVER_PORT}
      XFORM_JWT_SECRET: ${XFORM_JWT_SECRET}
      XFORM_CONFIGURATIONS_ORGANIZATIONS: /configuration/organizations.json
      XFORM_CONFIGURATIONS_PIPELINES: /configuration/pipelines.json
      XFORM_CONFIGURATIONS_SOLUTIONS: /configuration/solutions.json
      XFORM_CONFIGURATIONS_MAPPINGS: /configuration/mappings.json
      XFORM_CONFIGURATIONS_ACCESS-CONTROL: /configuration/access-control.json
      XFORM_CONFIGURATIONS_OPERATION-PRECONDITION-FIELDS: /configuration/operation-precondition-fields.json
      XFORM_CONFIGURATIONS_USERS: /configuration/users.json
      XFORM_CONFIGURATIONS_GROUP-ROLE-MAPPING: /configuration/group-role-mapping.json
      XFORM_CRYPTO_STORE_KEY_TOMCAT_SERVER_FILE: /ssl/server_keystore.bcfks
      XFORM_CRYPTO_STORE_KEY_WS_CLIENT_FILE: /ssl/server_keystore.bcfks
      XFORM_CRYPTO_STORE_TRUST_TOMCAT_SERVER_FILE: /ssl/server_keystore.bcfks
      XFORM_CRYPTO_STORE_TRUST_WS_CLIENT_FILE: /ssl/client_keystore.bcfks
      xform.allow-delete-via-api: true
      LOGGING_LEVEL: ${LOGGING_LEVEL}
    volumes:
      - type: bind
        source: ${SSL_SOURCE}
        target: /ssl
      - type: bind
        source: ${CONFIG_SOURCE}
        target: /configuration
    networks:
      - izg-shared-network

networks:
  izg-shared-network:
    external: true