name: Java CI with Maven

on:
  workflow_call:
    secrets:
      ACTIONS_KEY:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check version format in develop branch
        if: github.ref == 'refs/heads/IGDD-1697_pipeline_improvements'
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]]; then
            echo "Version $VERSION is not in the correct format. It should be #.#.#-SNAPSHOT."
            exit 1
          fi
          echo "Version $VERSION is in the correct format for common2."

# More to come...
