name: Java CI with Maven

on:
  push:
    branches:
      - IGDD-1697_pipeline_improvementsxyz

# Ensure only one build changes dev environment at the same time
concurrency: dev

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.checkout.outputs.workspace }}
    steps:
      - name: Checkout the software
        id: checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.ACTIONS_KEY}}

  call-workflow-passing-data:
    needs: checkout
    uses: ./.github/workflows/common.yml
    with:
      workspace: ${{ needs.checkout.outputs.workspace }}
    secrets:
      ACTIONS_KEY: ${{ secrets.GITHUB_TOKEN }}
