name: Java CI with Maven

on:
  push:
    branches:
      - IGDD-1697_pipeline_improvements

# Ensure only one build changes dev environment at the same time
concurrency: dev

jobs:
  build:
    uses: .//.github/workflows/common.yml
    secrets:
        ACTIONS_KEY: ${{secrets.ACTIONS_KEY}}

# More to come...
