name: Java CI with Maven

on:
  push:
    branches:
      - IGDD-1697_pipeline_improvements

# Ensure only one build changes dev environment at the same time
concurrency: dev

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the software
        uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.ACTIONS_KEY}}

  build:
    uses: ./.github/workflows/common.yml
    secrets:
        ACTIONS_KEY: ${{secrets.ACTIONS_KEY}}

  additional-build:
    uses: ./.github/workflows/common2.yml
    secrets:
      ACTIONS_KEY: ${{secrets.ACTIONS_KEY}}

# More to come...
